f = open("D:\\Sem 1\\git\\git-rebase\\Main.txt","r")
data = f.read()
print(data)
print(type(data))
f.close()

f = open("D:\\Sem 1\\git\\git-rebase\\Main.txt","r")
data = f.read(4)
print(data)
print(type(data))
f.close()

f = open("D:\\Sem 1\\git\\git-rebase\\Main.txt","r")
line1 = f.readline()
print(line1)
line2 = f.readline()
print(line2)
line3 = f.readline()
print(line3)
line4 = f.readline()
print(line4)
line5 = f.readline()
print(line5)
line6 = f.readline()
print(line6)
f.close()
